---
name: Level 1 Research Branch
on:
  workflow_dispatch:

env:
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Initialize
        run: nix-shell -p coreutils --run 'echo "Starting" > init.txt'
      - name: Research
        run: |
          nix-shell -p nodejs expect --run 'expect -c "
            set timeout 120
            spawn npx @anthropic-ai/claude-code --dangerously-skip-permissions \"Research: tools\"
            expect { -re {.*bypass permissions.*} { send \"2\r\" } }
            expect { -re {.*research.*|.*Write.*} { exit 0 } timeout { exit 1 } }
          "'
      - name: Results
        run: nix-shell -p coreutils --run 'echo "Complete" > results.txt'
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            init.txt
            results.txt
